# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

if Category.count == 0
  Category.create!(name: 'Hello')
  Category.create!(name: 'Community')
  Category.create!(name: 'Games')
  Category.create!(name: 'Developers')
  Category.create!(name: 'Web')
  Category.create!(name: 'Hardware')
end

if Topic.count == 0
  Topic.create!(name: 'Linguagens', category_id: 4, topic_id: nil, description: 'Linguagem de programação.', logged: false)
  Topic.create!(name: 'Python', category_id: 4, topic_id: 1, description: 'Linguagem de programação.', logged: false)
  Topic.create!(name: 'Ruby', category_id: 4, topic_id: 1, description: 'Linguagem de programação.', logged: false)
  Topic.create!(name: 'PHP', category_id: 4, topic_id: 1, description: 'Linguagem de programação.', logged: false)
  Topic.create!(name: 'Java', category_id: 4, topic_id: 1, description: 'Linguagem de programação.', logged: false)
  Topic.create!(name: 'C++', category_id: 4, topic_id: 1, description: 'Linguagem de programação.', logged: false)
  Comment.create!(post_id: 1, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
  Comment.create!(post_id: 2, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
  Comment.create!(post_id: 3, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
  Comment.create!(post_id: 4, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')

end

if !Category.find_by_name('Geral')
  Category.create!(name:'Geral', logged:false)
end

Post.create!(name: "Aprendendo Python", topic_id: 2, user_id: 1, logged: false)
Post.create!(name: "Aprendendo Python 2", topic_id: 2, user_id: 1, logged: false)
Post.create!(name: "Aprendendo Ruby", topic_id: 3, user_id: 1, logged: false)
Post.create!(name: "Aprendendo Ruby 2", topic_id: 3, user_id: 1, logged: false)

#
# Comment.create!(post_id: 9, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 9, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 9, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 8, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 8, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 7, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 7, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 6, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 6, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 5, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 5, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 4, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 3, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 2, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 2, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 1, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
#
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')
# Comment.create!(post_id: 10, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis.')


# topic = Topic.find_by_name('Linguagens')
# topic.topic_id = nil
# topic.save
#
# topics = Topic.all
# topics.each do |t|
#   if t.id != topic.id
#     t.topic_id = topic.id
#     t.save
#   end
# end

# for i in 1..9
#   Post.create!(name: "Testando {i}", topic_id: 6, user_id: 1, content: 'Mussum ipsum cacilds, vidis litro abertis. Consetis adipiscings elitis. Pra lá , depois divoltis porris, paradis. Paisis, filhis, espiritis santis. Mé faiz elementum girarzis, nisi eros vermeio, in elementis mé pra quem é amistosis quis leo. Manduma pindureta quium dia nois paga. Sapien in monti palavris qui num significa nadis i pareci latim. Interessantiss quisso pudia ce receita de bolis, mais bolis eu num gostis. \nSuco de cevadiss, é um leite divinis, qui tem lupuliz, matis, aguis e fermentis. Interagi no mé, cursus quis, vehicula ac nisi. Aenean vel dui dui. Nullam leo erat, aliquet quis tempus a, posuere ut mi. Ut scelerisque neque et turpis posuere pulvinar pellentesque nibh ullamcorper. Pharetra in mattis molestie, volutpat elementum justo. Aenean ut ante turpis. Pellentesque laoreet mé vel lectus scelerisque interdum cursus velit auctor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ac mauris lectus, non scelerisque augue. Aenean justo massa.')
# end
